sudo: required
services:
  - docker

before_install:
  - docker build -t moussavdb/runtime-java:latest -t moussavdb/runtime-java:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/runtime-java
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/runtime-java:latest;
    docker push moussavdb/runtime-java:build_$TRAVIS_BUILD_NUMBER;
